
-- REPAIR: ADD 'sold_by_id' TO SALES TABLE FOR INCENTIVE TRACKING
ALTER TABLE IF EXISTS public.sales 
ADD COLUMN IF NOT EXISTS sold_by_id TEXT;

-- REFRESH POLICIES AND PERMISSIONS
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.sales TO anon, authenticated, postgres;
