import { reportService } from './reportService';
import { db } from './mockSupabase';
import { format, parseISO } from 'date-fns';

export const emailService = {
  async sendEmail(to: string, subject: string, html: string, attachments: { filename: string; content: string }[] = []) {
    console.log(`[Email Service] Dispatching email to: ${to}`);
    console.log(`[Email Service] Subject: ${subject}`);
    console.log(`[Email Service] Attachments: ${attachments.length}`);
    await new Promise(resolve => setTimeout(resolve, 800));
    return { success: true, messageId: Math.random().toString(36).substring(7) };
  },

  async sendReportEmail(
    recipients: string,
    reportTitle: string,
    propertyName: string,
    outletName: string,
    pdfBase64: string,
    summaryText?: string
  ) {
    const toList = recipients.split(',').map(e => e.trim()).filter(Boolean);
    if (toList.length === 0) return { success: false, error: 'No recipient email addresses provided' };

    const dateStr = format(new Date(), 'dd MMM yyyy');
    const subject = `${reportTitle} - ${propertyName} (${outletName}) - ${dateStr}`;
    const filename = `${reportTitle.replace(/[^a-zA-Z0-9]/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f8fafc; color: #0f172a; margin: 0; padding: 20px; }
          .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 20px; padding: 32px; border: 1px solid #e2e8f0; }
          .header { border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
          .title { font-size: 20px; font-weight: 800; text-transform: uppercase; color: #0f172a; margin: 0; }
          .subtitle { font-size: 11px; font-weight: 700; color: #6366f1; text-transform: uppercase; tracking: 0.1em; margin-top: 4px; }
          .meta { background: #f1f5f9; padding: 16px; border-radius: 12px; margin: 20px 0; font-size: 13px; }
          .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 16px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1 class="title">${propertyName}</h1>
            <div class="subtitle">${reportTitle} &bull; ${outletName}</div>
          </div>
          <p>Please find attached the official <strong>${reportTitle}</strong> generated on ${format(new Date(), 'dd MMMM yyyy HH:mm')}.</p>
          ${summaryText ? `<div class="meta">${summaryText}</div>` : ''}
          <p>The detailed audit ledger is attached as a PDF document for your records.</p>
          <div class="footer">
            Generated by TTH Health Club Management System &bull; Confidential Audit Trail
          </div>
        </div>
      </body>
      </html>
    `;

    for (const recipient of toList) {
      await this.sendEmail(recipient, subject, html, [{ filename, content: pdfBase64 }]);
    }
    return { success: true, count: toList.length };
  },

  async sendMemberPurchaseEmail(member: any) {
    try {
      const properties = await db.getProperties();
      const outlets = await db.getOutlets();
      const recipients = await db.getReportRecipients();
      const settings = await db.getSettings();
      const currencies = await db.getCurrencies();

      const outlet = outlets.find(o => o.id === member.outlet_id);
      const property = outlet ? properties.find(p => p.id === outlet.property_id) : properties[0];
      const currency = (settings && currencies.find(c => c.id === settings.currency_id)) || currencies[0];
      const symbol = currency?.symbol || 'QAR';

      // Find recipients configured for member_purchased, or all active recipients for outlet
      let targetEmails: string[] = [];
      const purchasedRecipients = recipients.filter(r => r.is_active && r.report_type === 'member_purchased' && (r.outlet_id === 'all' || r.outlet_id === member.outlet_id));
      
      if (purchasedRecipients.length > 0) {
        targetEmails = purchasedRecipients.flatMap(r => r.email.split(',').map(e => e.trim()));
      } else {
        const activeRecipients = recipients.filter(r => r.is_active && (r.outlet_id === 'all' || r.outlet_id === member.outlet_id));
        targetEmails = activeRecipients.flatMap(r => r.email.split(',').map(e => e.trim()));
      }

      if (member.email && member.email.trim() && !targetEmails.includes(member.email.trim())) {
        targetEmails.push(member.email.trim());
      }

      targetEmails = Array.from(new Set(targetEmails.filter(Boolean)));
      if (targetEmails.length === 0) {
        console.log('[Email Service] No recipient emails found for member purchase notification.');
        return;
      }

      const contractTemplate = outlet?.contract_template || (property as any)?.contract_template || (settings as any)?.contract_template || 'Standard Health Club Membership Agreement';
      const termsConditions = outlet?.conditions || (property as any)?.conditions || (settings as any)?.conditions || 'All club rules and regulations apply.';

      const startDateFormatted = member.start_date ? format(parseISO(member.start_date), 'dd MMM yyyy') : 'N/A';
      const endDateFormatted = (member.current_end_date || member.original_end_date) ? format(parseISO(member.current_end_date || member.original_end_date), 'dd MMM yyyy') : 'N/A';

      const subject = `Membership Purchase Confirmed - ${member.guest_name} (${member.membership_number})`;
      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #f8fafc; color: #0f172a; margin: 0; padding: 20px; line-height: 1.5; }
            .container { max-width: 650px; margin: 0 auto; background: #ffffff; border-radius: 24px; padding: 40px; border: 1px solid #e2e8f0; }
            .badge { display: inline-block; background: #dcfce7; color: #166534; font-size: 10px; font-weight: 800; text-transform: uppercase; padding: 4px 12px; border-radius: 999px; letter-spacing: 0.1em; margin-bottom: 12px; }
            .header { border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 24px; }
            .title { font-size: 24px; font-weight: 900; color: #0f172a; margin: 0; text-transform: uppercase; }
            .subtitle { font-size: 12px; font-weight: 700; color: #64748b; text-transform: uppercase; margin-top: 4px; }
            .details-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; background: #f8fafc; padding: 24px; border-radius: 16px; border: 1px solid #e2e8f0; margin: 24px 0; }
            .detail-item { font-size: 12px; }
            .detail-label { font-size: 9px; font-weight: 800; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }
            .detail-value { font-size: 14px; font-weight: 800; color: #0f172a; margin-top: 2px; }
            .amount-box { background: #1e1b4b; color: #ffffff; padding: 20px; border-radius: 16px; text-align: center; margin: 24px 0; }
            .amount-val { font-size: 28px; font-weight: 900; color: #818cf8; }
            .agreement-box { background: #fafafa; border: 1px solid #e5e5e5; padding: 20px; border-radius: 12px; font-size: 11px; color: #404040; margin-top: 24px; white-space: pre-wrap; }
            .footer { text-align: center; font-size: 11px; color: #94a3b8; margin-top: 32px; border-top: 1px solid #f1f5f9; padding-top: 16px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="badge">Purchase Confirmed</div>
            <div class="header">
              <h1 class="title">${property?.name || 'TTH Club'}</h1>
              <div class="subtitle">${outlet?.name || 'Main Facility'} &bull; Membership Enrollment</div>
            </div>

            <p>A new membership agreement has been completed and registered in the system:</p>

            <div class="details-grid">
              <div class="detail-item">
                <div class="detail-label">Member Name</div>
                <div class="detail-value">${member.guest_name}</div>
              </div>
              <div class="detail-item">
                <div class="detail-label">Membership Number</div>
                <div class="detail-value">${member.membership_number}</div>
              </div>
              <div class="detail-item">
                <div class="detail-label">Package & Access</div>
                <div class="detail-value">${member.package_type || 'Single'} (${member.access_type || 'Both'})</div>
              </div>
              <div class="detail-item">
                <div class="detail-label">Membership Type</div>
                <div class="detail-value">${member.membership_type || 'New'}</div>
              </div>
              <div class="detail-item">
                <div class="detail-label">Start Date</div>
                <div class="detail-value">${startDateFormatted}</div>
              </div>
              <div class="detail-item">
                <div class="detail-label">End Date (Validity)</div>
                <div class="detail-value">${endDateFormatted}</div>
              </div>
            </div>

            <div class="amount-box">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #a5b4fc;">Total Amount Paid</div>
              <div class="amount-val">${symbol} ${(member.net_amount || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</div>
              <div style="font-size: 11px; color: #cbd5e1; margin-top: 4px;">Check / Ref: ${member.check_no || 'Direct Purchase'}</div>
            </div>

            <div style="font-weight: 800; font-size: 12px; text-transform: uppercase; color: #0f172a; margin-top: 24px;">Signed Membership Agreement & Terms</div>
            <div class="agreement-box">
<strong>AGREEMENT TERMS:</strong>
${contractTemplate}

<strong>CONDITIONS & RULES:</strong>
${termsConditions}
            </div>

            <div class="footer">
              TTH Health Club Management System &bull; Verified Member Enrollment Dispatch
            </div>
          </div>
        </body>
        </html>
      `;

      for (const email of targetEmails) {
        await this.sendEmail(email, subject, html);
      }
      console.log(`[Email Service] Member purchase notification email sent to: ${targetEmails.join(', ')}`);
    } catch (err) {
      console.error('[Email Service] Error sending member purchase email:', err);
    }
  }
};

export const schedulerService = {
  async processScheduledReports() {
    const now = new Date();
    const currentTime = format(now, 'HH:mm');
    
    try {
      const recipients = await db.getReportRecipients();
      const properties = await db.getProperties();
      const outlets = await db.getOutlets();

      for (const recipient of recipients) {
        if (!recipient.is_active) continue;
        
        // Check if it's time to send
        if (recipient.send_time === currentTime) {
          console.log(`[Scheduler] Triggering report for ${recipient.email} at ${recipient.send_time}`);
          
          const property = properties.find(p => p.id === recipient.property_id);
          if (!property) continue;

          const outlet = recipient.outlet_id === 'all' 
            ? 'all' 
            : outlets.find(o => o.id === recipient.outlet_id);
          
          if (!outlet) continue;

          // Generate Report
          const pdf = await reportService.generateDailyRevenuePDF(property, outlet, now);
          const pdfBase64 = pdf.output('datauristring').split(',')[1];
          
          // Generate Email HTML
          const html = await reportService.generateEmailTemplate(property, outlet, now);
          
          // Send Email
          await emailService.sendEmail(
            recipient.email,
            `Daily Revenue Report - ${property.name} - ${format(now, 'dd MMM yyyy')}`,
            html,
            [{ filename: `Daily_Revenue_${format(now, 'yyyyMMdd')}.pdf`, content: pdfBase64 }]
          );
        }
      }
    } catch (error) {
      console.error('[Scheduler] Error processing reports:', error);
    }
  }
};
