import React from 'react';
import { format } from 'date-fns';
import { useSettings } from '../contexts/SettingsContext';
import { getDeviceSessionItem } from '../services/deviceStorage';

interface ReportAuditFooterProps {
  isEmbedded?: boolean;
  generatedBy?: string;
  isAutoGenerated?: boolean;
}

export const ReportAuditFooter: React.FC<ReportAuditFooterProps> = ({ isEmbedded, generatedBy, isAutoGenerated }) => {
  const { currentProperty } = useSettings();
  const session = JSON.parse(getDeviceSessionItem('membership_session') || '{}');
  const exporterName = isAutoGenerated ? 'SYSTEM AUTOMATED' : (generatedBy || (session?.name ? session.name : 'SYSTEM AUTOMATED'));

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        @page {
          margin: 8mm;
        }
        @media print {
          .print-audit-footer {
            display: flex !important;
            margin-top: 1.5rem !important;
            padding-top: 1rem !important;
            border-top: 1px solid #e2e8f0 !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          /* Hide the audit footer if it's embedded in a container that already has a global footer (like Reports.tsx) */
          .report-container-context .print-audit-footer {
            display: none !important;
          }
        }
      `}} />
      
      {/* Full Audit Trail - Appears at the end of report content */}
      <div className={`print-audit-footer mt-12 pt-6 border-t border-slate-100 flex justify-between items-center ${isEmbedded ? 'text-[8px]' : 'text-[10px]'} font-black text-slate-300 uppercase tracking-widest print:flex hidden`}>
        <span>
          OFFICIAL FACILITY REPORT
        </span>
        <span className="text-slate-400">
          Exported on: {format(new Date(), 'dd-MMM-yyyy HH:mm:ss')} by {exporterName}
        </span>
        <span>
          &copy; {new Date().getFullYear()} {currentProperty?.name || 'System'}. All rights reserved.
        </span>
      </div>
    </>
  );
};
